name: flutter_list_demo
description: A flutter list app.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  easy_refresh: ^3.0.4+2
  event_bus: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.9
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
